services:
  postgres:
    image: postgres:14
    restart: 'no'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "pg_test_data:/var/lib/postgresql/data"

volumes:
  pg_test_data: